[versions]
kotlin = "1.6.10"
kotest = "5.4.2"
compose = "1.1.0"
datastore = "1.0.0"
androidx = "1.4.0"
koin = "3.2.0-beta-1"
vanpra-material-dialogs = "0.6.3"
detekt = "1.21.0-RC1"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[libraries]
android-desugar-jdk = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.5" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.5.1" }

kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-dialogs-core = { module = "io.github.vanpra.compose-material-dialogs:core", version.ref = "vanpra-material-dialogs" }
compose-material-dialogs-date-time = { module = "io.github.vanpra.compose-material-dialogs:datetime", version.ref = "vanpra-material-dialogs" }
compose-tabler-icons = { module = "br.com.devsrsouza.compose.icons.android:tabler-icons", version = "1.0.0" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-material-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-test = { module = "androidx.compose.ui:ui-test", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.3.1" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version = "2.5.1" }

datastore-android = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }

junit4 = { module = "junit:junit", version = "4.13" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx" }

graph-view = { module = "com.jjoe64:graphview", version = "4.2.2" }
mp-android-chart = { module = "com.github.PhilJay:MPAndroidChart", version = "v3.1.0" }

apache-commons-lang = { module = "org.apache.commons:commons-lang3", version = "3.12.0" }
apache-commons-math = { module = "org.apache.commons:commons-math3", version = "3.6.1" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }

joda-time = { module = "joda-time:joda-time", version = "2.10.13" }
kotlin-date-range = { module = "me.moallemi.tools:kotlin-date-range", version = "1.0.0" }

mockk = { module = "io.mockk:mockk", version = "1.12.0" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
snodge = { module = "com.natpryce:snodge", version = "3.7.0.0" }
kotlin-csv = { module = "com.github.doyaaaaaken:kotlin-csv-jvm", version = "1.2.0" }


[bundles]
kotest-all = ["kotest-property", "kotest-assertions", "kotest-runner-junit5"]
kotest-extras = ["kotest-property", "kotest-assertions"]
compose = ["compose-material", "compose-material-icons", "compose-tabler-icons", "compose-activity", "compose-navigation", "compose-material-dialogs-core", "compose-material-dialogs-date-time"]
compose-test = ["compose-ui-test", "compose-ui-test-junit4"]
datastore = ["datastore-android", "datastore-core"]
androidx-test = ["androidx-test-rules", "androidx-test-runner", "junit4"]
graph-view = ["graph-view", "mp-android-chart"]
apache-commons = ["apache-commons-lang", "apache-commons-math"]
koin = ["koin-android", "koin-compose"]
date-time = ["joda-time", "kotlin-date-range"]
